from enum import Enum

class AllureTags(str, Enum):
    COURSES = "COURSES"
    DASHBOARD = "DASHBOARD"
    AUTHORIZATION = "AUTHORIZATION"
    REGISTRATION = "REGISTRATION"
    REGRESSION = "REGRESSION"
    USER_LOGIN = "USER_LOGIN"
    NAVIGATION = "NAVIGATION"